"use client";
import {FormEvent,useMemo,useState} from "react";

type Lead={id:number;name:string;age:number;interest:string;phone:string;instagram:string;createdAt:string};
type Schedule={id:number;category:string;label:string;active:boolean;position:number};
type Response={id:number;name:string;phone:string;category:string;scheduleId:number|null;scheduleLabel:string;suggestedTime:string;createdAt:string};
type Feedback={id:number;name:string;interest:string;message:string;approved:boolean;createdAt:string};
type Tab="demand"|"schedules"|"leads"|"feedbacks";

export default function AdminDashboard({initialLeads,initialSchedules,initialResponses,initialFeedbacks}:{initialLeads:Lead[];initialSchedules:Schedule[];initialResponses:Response[];initialFeedbacks:Feedback[]}){
  const[tab,setTab]=useState<Tab>("demand"),[leads,setLeads]=useState(initialLeads),[schedules,setSchedules]=useState(initialSchedules),[responses,setResponses]=useState(initialResponses),[feedbacks,setFeedbacks]=useState(initialFeedbacks),[busy,setBusy]=useState("");
  const demand=useMemo(()=>schedules.map(schedule=>({...schedule,total:responses.filter(r=>r.scheduleId===schedule.id).length})).sort((a,b)=>b.total-a.total),[schedules,responses]);
  const suggestions=useMemo(()=>responses.filter(r=>r.suggestedTime.trim()),[responses]);
  const categories=useMemo(()=>Array.from(new Set(schedules.map(item=>item.category))).sort((a,b)=>a.localeCompare(b,"pt-BR")),[schedules]);
  async function remove(kind:"lead"|"response"|"feedback"|"schedule",id:number,label:string){if(!confirm(`Excluir ${label}? Esta ação não poderá ser desfeita.`))return;setBusy(`${kind}-${id}`);const paths={lead:"leads",response:"schedule-responses",feedback:"feedbacks",schedule:"schedules"};const r=await fetch(`/api/admin/${paths[kind]}?id=${id}`,{method:"DELETE"});if(r.ok){if(kind==="lead")setLeads(x=>x.filter(i=>i.id!==id));if(kind==="response")setResponses(x=>x.filter(i=>i.id!==id));if(kind==="feedback")setFeedbacks(x=>x.filter(i=>i.id!==id));if(kind==="schedule")setSchedules(x=>x.filter(i=>i.id!==id))}setBusy("")}
  async function addSchedule(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("add");const form=e.currentTarget;const r=await fetch("/api/admin/schedules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(r.ok){const created=await r.json();setSchedules(x=>[...x,created]);form.reset()}setBusy("")}
  async function toggleSchedule(item:Schedule){setBusy(`schedule-${item.id}`);const r=await fetch("/api/admin/schedules",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,active:!item.active})});if(r.ok)setSchedules(x=>x.map(i=>i.id===item.id?{...i,active:!i.active}:i));setBusy("")}
  async function renameSchedule(item:Schedule){const label=prompt("Novo nome/descrição do horário:",item.label)?.trim();if(!label||label===item.label)return;if(label.length>50){alert("O horário deve ter no máximo 50 caracteres.");return}setBusy(`schedule-${item.id}`);const r=await fetch("/api/admin/schedules",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,label})});if(r.ok)setSchedules(current=>current.map(schedule=>schedule.id===item.id?{...schedule,label}:schedule));else alert("Não foi possível renomear o horário.");setBusy("")}
  async function moveSchedule(item:Schedule,direction:-1|1){const ordered=schedules.filter(schedule=>schedule.category===item.category).sort((a,b)=>a.position-b.position||a.id-b.id),index=ordered.findIndex(schedule=>schedule.id===item.id),target=index+direction;if(index<0||target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];const positions=new Map(ordered.map((schedule,position)=>[schedule.id,position]));setBusy(`schedule-${item.id}`);const r=await fetch("/api/admin/schedules",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({orderedIds:ordered.map(schedule=>schedule.id)})});if(r.ok)setSchedules(current=>current.map(schedule=>positions.has(schedule.id)?{...schedule,position:positions.get(schedule.id)!}:schedule));else alert("Não foi possível alterar a ordem.");setBusy("")}
  async function renameCategory(category:string){const next=prompt(`Novo nome para ${category}:`,category)?.trim();if(!next||next===category)return;if(next.length<2||next.length>60){alert("O nome da turma deve ter entre 2 e 60 caracteres.");return}const items=schedules.filter(item=>item.category===category);setBusy(`category-${category}`);const results=await Promise.all(items.map(item=>fetch("/api/admin/schedules",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,category:next})})));if(results.every(result=>result.ok))setSchedules(current=>current.map(item=>item.category===category?{...item,category:next}:item));else alert("Não foi possível renomear todos os horários desta turma.");setBusy("")}
  async function removeCategory(category:string){const items=schedules.filter(item=>item.category===category);if(!confirm(`Excluir a turma ${category} e seus ${items.length} horário(s)? As respostas já recebidas serão mantidas.`))return;setBusy(`category-${category}`);const results=await Promise.all(items.map(item=>fetch(`/api/admin/schedules?id=${item.id}`,{method:"DELETE"})));if(results.every(result=>result.ok))setSchedules(current=>current.filter(item=>item.category!==category));else alert("Não foi possível excluir todos os horários desta turma.");setBusy("")}
  async function toggleFeedback(item:Feedback){setBusy(`feedback-${item.id}`);const r=await fetch("/api/admin/feedbacks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,approved:!item.approved})});if(r.ok)setFeedbacks(x=>x.map(i=>i.id===item.id?{...i,approved:!i.approved}:i));setBusy("")}
  const date=(value:string)=>new Date(value+(/Z$/.test(value)?"":"Z")).toLocaleDateString("pt-BR");
  return <><nav className="adminTabs" aria-label="Seções do painel"><button className={tab==="demand"?"active":""} onClick={()=>setTab("demand")}>Demanda <b>{responses.length}</b></button><button className={tab==="schedules"?"active":""} onClick={()=>setTab("schedules")}>Horários <b>{schedules.length}</b></button><button className={tab==="leads"?"active":""} onClick={()=>setTab("leads")}>Interessados <b>{leads.length}</b></button><button className={tab==="feedbacks"?"active":""} onClick={()=>setTab("feedbacks")}>Depoimentos <b>{feedbacks.length}</b></button></nav>
  {tab==="demand"&&<section className="adminPanel"><div className="panelHeading"><div><span>PESQUISA DE HORÁRIOS</span><h2>DEMANDA POR TURMA</h2></div><p>Veja os horários mais escolhidos e as sugestões recebidas.</p></div><div className="demandGrid">{demand.map(item=><article key={item.id}><small>{item.category}</small><strong>{item.label}</strong><b>{item.total}</b><span>interessado(s)</span></article>)}{!demand.length&&<div className="adminEmpty">Cadastre horários para começar a pesquisa.</div>}</div><h3 className="subTitle">RESPOSTAS RECEBIDAS</h3><div className="table"><table><thead><tr><th>Data</th><th>Nome</th><th>Turma</th><th>Horário</th><th>Sugestão</th><th>WhatsApp</th><th></th></tr></thead><tbody>{responses.map(row=><tr key={row.id}><td>{date(row.createdAt)}</td><td><b>{row.name}</b></td><td>{row.category}</td><td>{row.scheduleLabel}</td><td>{row.suggestedTime||"—"}</td><td><a className="whats" href={`https://wa.me/55${row.phone.replace(/\D/g,"")}`} target="_blank">{row.phone}</a></td><td><button className="dangerLink" disabled={busy===`response-${row.id}`} onClick={()=>remove("response",row.id,"esta resposta")}>Excluir</button></td></tr>)}</tbody></table>{!responses.length&&<div className="adminEmpty">Nenhuma resposta recebida ainda.</div>}</div>{suggestions.length>0&&<><h3 className="subTitle">HORÁRIOS SUGERIDOS</h3><div className="suggestionList">{suggestions.map(item=><article key={item.id}><b>{item.suggestedTime}</b><span>{item.category} · {item.name}</span></article>)}</div></>}
  </section>}
  {tab==="schedules"&&<section className="adminPanel"><div className="panelHeading"><div><span>CONFIGURAÇÃO</span><h2>TURMAS E HORÁRIOS DISPONÍVEIS</h2></div><p>Adicione quantos horários quiser. Use as setas para definir a ordem exibida no site.</p></div><form className="scheduleCreator" onSubmit={addSchedule}><label>Nome da turma<input name="category" list="schedule-categories" required minLength={2} maxLength={60} placeholder="Ex.: Jiu-Jitsu Adulto"/><datalist id="schedule-categories">{categories.map(category=><option key={category} value={category}/>)}</datalist></label><label>Horário / descrição<input name="label" required maxLength={50} placeholder="Ex.: 12h ou Terça e quinta — 19h"/></label><button className="button" disabled={busy==="add"}>ADICIONAR HORÁRIO</button></form><div className="scheduleColumns">{categories.map(category=>{const ordered=schedules.filter(s=>s.category===category).sort((a,b)=>a.position-b.position||a.id-b.id);return <div key={category}><div className="categoryTitle"><h3>{category}</h3><div><button className="smallAction" disabled={busy===`category-${category}`} onClick={()=>renameCategory(category)}>Renomear</button><button className="dangerLink" disabled={busy===`category-${category}`} onClick={()=>removeCategory(category)}>Excluir turma</button></div></div>{ordered.map((item,index)=><article className={!item.active?"inactive":""} key={item.id}><div><b>{item.label}</b><small>{responses.filter(r=>r.scheduleId===item.id).length} interessado(s)</small></div><div className="scheduleActions"><span className="orderActions"><button className="smallAction" disabled={index===0||busy===`schedule-${item.id}`} title="Mover para cima" aria-label={`Mover ${item.label} para cima`} onClick={()=>moveSchedule(item,-1)}>↑</button><button className="smallAction" disabled={index===ordered.length-1||busy===`schedule-${item.id}`} title="Mover para baixo" aria-label={`Mover ${item.label} para baixo`} onClick={()=>moveSchedule(item,1)}>↓</button></span><button className="smallAction" disabled={busy===`schedule-${item.id}`} onClick={()=>renameSchedule(item)}>Renomear</button><button className="smallAction" disabled={busy===`schedule-${item.id}`} onClick={()=>toggleSchedule(item)}>{item.active?"Pausar":"Ativar"}</button><button className="dangerLink" disabled={busy===`schedule-${item.id}`} onClick={()=>remove("schedule",item.id,`o horário ${item.label}`)}>Excluir</button></div></article>)}</div>})}{!categories.length&&<div className="adminEmpty">Cadastre a primeira turma e o primeiro horário.</div>}</div></section>}
  {tab==="leads"&&<section className="adminPanel"><div className="panelHeading"><div><span>CONTATOS</span><h2>INTERESSADOS</h2></div><p>Cadastros recebidos pelo formulário anterior.</p></div><div className="table"><table><thead><tr><th>Data</th><th>Nome</th><th>Idade</th><th>Interesse</th><th>Telefone</th><th>Instagram</th><th></th></tr></thead><tbody>{leads.map(row=><tr key={row.id}><td>{date(row.createdAt)}</td><td><b>{row.name}</b></td><td>{row.age}</td><td>{row.interest}</td><td><a className="whats" href={`https://wa.me/55${row.phone.replace(/\D/g,"")}`} target="_blank">{row.phone}</a></td><td>{row.instagram||"—"}</td><td><button className="dangerLink" onClick={()=>remove("lead",row.id,"este cadastro")}>Excluir</button></td></tr>)}</tbody></table>{!leads.length&&<div className="adminEmpty">Nenhum interessado cadastrado.</div>}</div></section>}
  {tab==="feedbacks"&&<section className="adminPanel"><div className="panelHeading"><div><span>MODERAÇÃO</span><h2>DEPOIMENTOS</h2></div><p>Escolha quais experiências aparecem na página principal.</p></div><div className="feedbackAdminGrid">{feedbacks.map(item=><article className={item.approved?"published":""} key={item.id}><div className="feedbackMeta"><b>{item.name}</b><span>{item.interest}</span></div><p>“{item.message}”</p><div className="feedbackDecision"><small>{date(item.createdAt)}</small><div><button className="smallAction" onClick={()=>toggleFeedback(item)}>{item.approved?"Ocultar":"Publicar"}</button><button className="dangerLink" onClick={()=>remove("feedback",item.id,"este depoimento")}>Excluir</button></div></div></article>)}{!feedbacks.length&&<div className="adminEmpty">Nenhum depoimento recebido.</div>}</div></section>}
  </>
}
