"use client";import {FormEvent,useMemo,useState} from "react";
type Professor={id:number;name:string;username:string;active:boolean;createdAt:string};type ClassItem={id:number;name:string;category:string;scheduleLabel:string;active:boolean};type Assignment={classId:number;professorId:number};type Student={id:number;name:string;belt:string;active:boolean};type Membership={classId:number;studentId:number};type Attendance={classId:number;studentId:number;classDate:string;status:string};type Tab="professors"|"classes"|"students";
export default function SchoolAdmin({initialProfessors,initialClasses,initialAssignments,students,memberships,attendance}:{initialProfessors:Professor[];initialClasses:ClassItem[];initialAssignments:Assignment[];students:Student[];memberships:Membership[];attendance:Attendance[]}){const[tab,setTab]=useState<Tab>("professors"),[professors,setProfessors]=useState(initialProfessors),[classes,setClasses]=useState(initialClasses),[assignments,setAssignments]=useState(initialAssignments),[studentMemberships,setStudentMemberships]=useState(memberships),[status,setStatus]=useState(""),[belt,setBelt]=useState(""),[classFilter,setClassFilter]=useState(""),[minAbsences,setMinAbsences]=useState("0"),[from,setFrom]=useState(()=>{const d=new Date();d.setDate(d.getDate()-30);return d.toISOString().slice(0,10)}),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
async function addProfessor(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Criando acesso...");const form=e.currentTarget,r=await fetch("/api/admin/professors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(r.ok){const created=await r.json();setProfessors(x=>[...x,created]);form.reset();setStatus("Professor criado com sucesso.")}else setStatus((await r.json()).error??"Não foi possível criar.")}
async function toggleProfessor(item:Professor){const r=await fetch("/api/admin/professors",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,active:!item.active})});if(r.ok)setProfessors(x=>x.map(p=>p.id===item.id?{...p,active:!p.active}:p))}
async function resetPassword(item:Professor){const password=prompt(`Nova senha para ${item.name} (mínimo 6 caracteres):`);if(!password)return;if(password.length<6){setStatus("A nova senha precisa ter pelo menos 6 caracteres.");return}const r=await fetch("/api/admin/professors",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,password})});const result=await r.json().catch(()=>({}));setStatus(r.ok?`Senha de ${item.name} atualizada.`:result.error??"Não foi possível atualizar a senha.")}
async function deleteProfessor(item:Professor){if(!confirm(`Excluir o professor ${item.name}? O acesso dele será removido das turmas, mas as turmas e os alunos serão mantidos.`))return;setStatus("Excluindo professor...");const r=await fetch("/api/admin/professors",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id})});const result=await r.json().catch(()=>({}));if(r.ok){setProfessors(x=>x.filter(p=>p.id!==item.id));setAssignments(x=>x.filter(a=>a.professorId!==item.id));setStatus("Professor excluído. As turmas e os alunos foram mantidos.")}else setStatus(result.error??"Não foi possível excluir o professor.")}
async function addClass(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form),professorIds=data.getAll("professorIds").map(Number);const r=await fetch("/api/admin/classes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:data.get("name"),category:data.get("category"),scheduleLabel:data.get("scheduleLabel"),professorIds})});if(r.ok){const created=await r.json();setClasses(x=>[...x,created]);setAssignments(x=>[...x,...professorIds.map(professorId=>({classId:created.id,professorId}))]);form.reset();setStatus("Turma criada.")}else setStatus("Não foi possível criar a turma.")}
async function saveAssignments(classId:number,professorIds:number[]){const r=await fetch("/api/admin/classes",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({classId,professorIds})});if(r.ok){setAssignments(x=>[...x.filter(a=>a.classId!==classId),...professorIds.map(professorId=>({classId,professorId}))]);setStatus("Professores da turma atualizados.")}}
async function saveStudentClasses(studentId:number,classIds:number[]){const r=await fetch("/api/admin/student-classes",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({studentId,classIds})});if(r.ok){setStudentMemberships(x=>[...x.filter(m=>m.studentId!==studentId),...classIds.map(classId=>({studentId,classId}))]);setStatus("Turmas do aluno atualizadas.")}}
async function toggleClass(item:ClassItem){const r=await fetch("/api/admin/classes",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,active:!item.active})});if(r.ok)setClasses(x=>x.map(c=>c.id===item.id?{...c,active:!c.active}:c))}const belts=Array.from(new Set(students.map(s=>s.belt))).sort();const report=useMemo(()=>students.map(student=>{const classIds=studentMemberships.filter(m=>m.studentId===student.id).map(m=>m.classId),absences=attendance.filter(a=>a.studentId===student.id&&a.status==="absent"&&a.classDate>=from&&a.classDate<=to).length;return{...student,classIds,absences,classNames:classes.filter(c=>classIds.includes(c.id)).map(c=>c.name).join(", ")}}).filter(s=>(!belt||s.belt===belt)&&(!classFilter||s.classIds.includes(Number(classFilter)))&&s.absences>=Number(minAbsences||0)),[students,studentMemberships,attendance,classes,belt,classFilter,minAbsences,from,to]);return <section className="schoolAdmin"><div className="panelHeading"><div><span>GESTÃO ACADÊMICA</span><h2>PROFESSORES, TURMAS E ALUNOS</h2></div><p>Controle os acessos da equipe e acompanhe a frequência dos alunos.</p></div><nav className="schoolTabs">
<button className={tab==="professors"?"active":""} onClick={()=>setTab("professors")}>Professores</button>
<button className={tab==="classes"?"active":""} onClick={()=>setTab("classes")}>Turmas</button>
<button className={tab==="students"?"active":""} onClick={()=>setTab("students")}>Alunos e faltas</button></nav>{tab==="professors"&&<div className="schoolPane"><form className="managementForm" onSubmit={addProfessor}><label>Nome<input name="name" required/></label><label>Usuário<input name="username" required minLength={3} placeholder="professor.joao"/></label><label>Senha inicial<input name="password" type="password" required minLength={6}/></label>
<button className="button">CRIAR PROFESSOR</button></form><div className="managementList">{professors.map(p=><article className={!p.active?"inactive":""} key={p.id}><div><b>{p.name}</b><small>Usuário: {p.username}</small></div><div>
<button className="smallAction" onClick={()=>resetPassword(p)}>Alterar senha</button>
<button className="dangerLink" onClick={()=>deleteProfessor(p)}>Excluir</button>
<button className="dangerLink" onClick={()=>toggleProfessor(p)}>{p.active?"Bloquear":"Ativar"}</button></div></article>)}</div></div>}{tab==="classes"&&<div className="schoolPane"><form className="classForm" onSubmit={addClass}><label>Nome da turma<input name="name" required placeholder="Ex.: Adulto — Noite"/></label><label>Categoria<select name="category"><option>Adulto</option><option>Kids</option></select></label><label>Horário<input name="scheduleLabel" required placeholder="Ex.: Seg/Qua — 19h"/></label><fieldset><legend>Professores com acesso</legend>{professors.filter(p=>p.active).map(p=><label key={p.id}><input type="checkbox" name="professorIds" value={p.id}/>{p.name}</label>)}</fieldset>
<button className="button">CRIAR TURMA</button></form><div className="classAdminGrid">{classes.map(c=><ClassAccessCard key={c.id} item={c} professors={professors} selected={assignments.filter(a=>a.classId===c.id).map(a=>a.professorId)} onSave={ids=>saveAssignments(c.id,ids)} onToggle={()=>toggleClass(c)}/>)}</div></div>}{tab==="students"&&<div className="schoolPane"><div className="attendanceFilters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Mínimo de faltas<input type="number" min="0" value={minAbsences} onChange={e=>setMinAbsences(e.target.value)}/></label><label>Faixa<select value={belt} onChange={e=>setBelt(e.target.value)}><option value="">Todas</option>{belts.map(b=><option key={b}>{b}</option>)}</select></label><label>Turma<select value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option value="">Todas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="table"><table><thead><tr><th>Aluno</th><th>Faixa</th><th>Turmas</th><th>Faltas no período</th></tr></thead><tbody>{report.map(s=><tr key={s.id}><td><b>{s.name}</b></td><td>{s.belt}</td><td><StudentClassEditor studentId={s.id} classes={classes} selected={s.classIds} onSave={ids=>saveStudentClasses(s.id,ids)}/></td><td><strong className={s.absences>0?"absenceCount":""}>{s.absences}</strong></td></tr>)}</tbody></table>{!report.length&&<div className="adminEmpty">Nenhum aluno encontrado com esses filtros.</div>}</div></div>}<p className="managementStatus">{status}</p></section>}
function ClassAccessCard({item,professors,selected,onSave,onToggle}:{item:ClassItem;professors:Professor[];selected:number[];onSave:(ids:number[])=>void;onToggle:()=>void}){const[ids,setIds]=useState(selected);return <article className={!item.active?"inactive":""}><div className="classCardTitle"><div><small>{item.category}</small><h3>{item.name}</h3><b>{item.scheduleLabel}</b></div>
<button className="dangerLink" onClick={onToggle}>{item.active?"Pausar":"Ativar"}</button></div><div className="professorChecks">{professors.map(p=><label key={p.id}><input type="checkbox" checked={ids.includes(p.id)} onChange={e=>setIds(x=>e.target.checked?[...x,p.id]:x.filter(id=>id!==p.id))}/>{p.name}</label>)}</div>
<button className="smallAction saveAccess" onClick={()=>onSave(ids)}>Salvar acessos</button></article>}
function StudentClassEditor({studentId,classes,selected,onSave}:{studentId:number;classes:ClassItem[];selected:number[];onSave:(ids:number[])=>void}){const[ids,setIds]=useState(selected);return <details className="studentClasses"><summary>{classes.filter(c=>ids.includes(c.id)).map(c=>c.name).join(", ")||"Sem turma"}</summary><div>{classes.map(c=><label key={c.id}><input type="checkbox" checked={ids.includes(c.id)} onChange={e=>setIds(x=>e.target.checked?[...x,c.id]:x.filter(id=>id!==c.id))}/>{c.name}</label>)}
<button className="smallAction" onClick={()=>onSave(ids)}>Salvar</button></div></details>}
